### ISSUE TITLE
麦肯锡2009年中国消费者  城市群划分

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/sina#1]
<img width="424" alt="default" src="https://user-images.githubusercontent.com/12031874/30310677-3b410aac-97c4-11e7-9cc1-dad7fe44bb1d.PNG">

**Comment by Cloud2016** [comment]
<img width="585" alt="clustermap" src="https://user-images.githubusercontent.com/12031874/30311125-711d06ce-97c6-11e7-904b-e450ca8be712.PNG">

**Comment by Cloud2016** [comment]
![city](https://user-images.githubusercontent.com/12031874/30313980-d2766248-97d1-11e7-97de-1a0343b265ba.jpeg)

**Comment by Cloud2016** [comment]
![unnamed-chunk-1-1](https://user-images.githubusercontent.com/12031874/30574607-a36cdffc-9d2d-11e7-83f0-1534159c5a16.png)
![unnamed-chunk-2-1](https://user-images.githubusercontent.com/12031874/30574612-a6821838-9d2d-11e7-94cf-33016ad06c6d.png)
![unnamed-chunk-3-1](https://user-images.githubusercontent.com/12031874/30574613-a8520c7c-9d2d-11e7-8cba-cb7661aefa62.png)
![unnamed-chunk-4-1](https://user-images.githubusercontent.com/12031874/30574615-abc876d4-9d2d-11e7-93c5-7da0b9611826.png)
![unnamed-chunk-5-1](https://user-images.githubusercontent.com/12031874/30574617-ade98c50-9d2d-11e7-9a9b-8fd5666fe54c.png)
![unnamed-chunk-6-1](https://user-images.githubusercontent.com/12031874/30574618-b053841e-9d2d-11e7-8c40-7fde6279d012.png)
![unnamed-chunk-7-1](https://user-images.githubusercontent.com/12031874/30574620-b2c03242-9d2d-11e7-91b2-edbda967a542.png)
![unnamed-chunk-8-1](https://user-images.githubusercontent.com/12031874/30574622-b59187a0-9d2d-11e7-92b7-629bbce40d2f.png)
![unnamed-chunk-9-1](https://user-images.githubusercontent.com/12031874/30574625-b7d0be78-9d2d-11e7-98d2-35cd7a598423.png)
