### ISSUE TITLE
配置过程存放图片

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/sina#2]
<img width="569" alt="r2ubuntu" src="https://user-images.githubusercontent.com/12031874/30781552-8fd1f232-a153-11e7-9d9f-8f50ad869d87.png">
<img width="578" alt="r2centos7" src="https://user-images.githubusercontent.com/12031874/30781553-903df8c4-a153-11e7-8159-7fb53b545225.png">

**Comment by Cloud2016** [comment]
![installed_packages](https://user-images.githubusercontent.com/12031874/31042268-b55ba502-a5d6-11e7-8949-b0bf93f07f75.PNG)
![clickhouse2r_success](https://user-images.githubusercontent.com/12031874/31042269-b8def710-a5d6-11e7-8d34-0e1387f11de1.PNG)
