### ISSUE TITLE
本地浏览 RStudio Server

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/sina#3]
<img width="960" alt="rstudio" src="https://user-images.githubusercontent.com/12031874/30841631-f5424e52-a2af-11e7-9b80-1776aef6cd54.png">

**Comment by Cloud2016** [comment]
<img width="960" alt="r" src="https://user-images.githubusercontent.com/12031874/30841674-372a641c-a2b0-11e7-90aa-7c99f30173cf.png">
