### ISSUE TITLE
CRAN包增长情况和编程语言排行榜

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/sina#6]
![number-of-submitted-packages-to-cran](https://user-images.githubusercontent.com/12031874/31308711-04f9596a-abae-11e7-963e-2a508ab2e67b.png)
<img width="680" alt="tiobe" src="https://user-images.githubusercontent.com/12031874/31308712-055ea798-abae-11e7-9b27-cdfc920fd736.PNG">

**Comment by Cloud2016** [comment]
<img width="681" alt="python" src="https://user-images.githubusercontent.com/12031874/31308728-5e304566-abae-11e7-990b-8dde7474e1fc.PNG">

**Comment by Cloud2016** [comment]
<img width="680" alt="r" src="https://user-images.githubusercontent.com/12031874/31308769-fa2559ac-abae-11e7-9242-3b43fba1c126.PNG">
![wherer](https://user-images.githubusercontent.com/12031874/31308771-038496f2-abaf-11e7-9f9c-e62b869dfdc1.png)
![default](https://user-images.githubusercontent.com/12031874/31308775-087563f8-abaf-11e7-84c1-30d8b444837b.png)
